Models/ErrorViewModel.cs
using System;

namespace proposal_items.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Image.cs
using System;

namespace proposal_items.Models
{
    public class Image
    {
        public int Id { get; set; }

        public string Filename { get; set; }

    }
}

Models/Proposal.cs
using System;
using System.Collections.Generic;

namespace proposal_items.Models
{
    public class Proposal
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public List<ProposalItem> ProposalItems { get; set; }

    }
}

Models/ProposalItem.cs
using System;

namespace proposal_items.Models
{
    public class ProposalItem
    {
        public int Id { get; set; }

        public int ProposalId { get; set; }

        public Proposal Proposal { get; set; }

        public int ImageId { get; set; }

        public Image Image { get; set; }
        
        public string Caption { get; set; }



    }
}

ViewModels/AddProposalItem.cs
using System.Collections.Generic;
using proposal_items.Models;

namespace proposal_items.ViewModels
{
    // a view model to be used with the AddProposalItem view
    // this one might not be necessary... a ProposalItem model
    // might be sufficient.
    public class AddProposalItem
    {
        public int ProposalId { get; set; }

        public int ImageId { get; set; }
        
        public Image Image { get; set; }

        public string Caption { get; set; }
    }
}

ViewModels/ImageSearch.cs
using System.Collections.Generic;
using proposal_items.Models;

namespace proposal_items.ViewModels
{
    // a view model to be used by the ImageSearch view/controller action.
    // holds the proposal id, search text, and the images that match the search text.
    public class ImageSearch
    {
        public int ProposalId { get; set; }
        public string SearchString { get; set; }

        public IEnumerable<Image> Images { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using proposal_items.Models;

namespace proposal_items.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProposalController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using proposal_items.Models;
using proposal_items.Services;
using proposal_items.ViewModels;

namespace proposal_items.Controllers
{
    public class ProposalController : Controller
    {
        private readonly Repository _repository;

        public ProposalController(Repository repository)
        {
            _repository = repository;
        }

        // GET: ToDo
        public ActionResult Index()
        {
            return View(_repository.Proposals);
        }

        public ActionResult SearchImages(int proposalId, string searchString) {
            // create an ImageSearch ViewModel that holds everything the view needs,
            // including the proposalId, search text, and image search results
            var vm = new ImageSearch {
                ProposalId = proposalId,
                SearchString = searchString,
                // search for images if there is search text
                Images = String.IsNullOrEmpty(searchString) 
                    ? _repository.Images
                    : _repository.Images.Where(i => i.Filename.Contains(searchString))
            };
            // pass the viewmodel to the view
            return View(vm);
        }

        public ActionResult AddProposalItem(int imageId, int proposalId) {
            // create an AddProposalItem view model to hold info for the view
            var vm = new AddProposalItem {
                ProposalId = proposalId,
                ImageId = imageId,
                // get the image object by id
                Image = _repository.Images.FirstOrDefault(i => i.Id == imageId),
                Caption = ""
            };
            // pass the view model to the view
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddProposalItem(int id, AddProposalItem vm) {
            // create a new proposalItem model and fill in the image id, caption, etc
            var newProposalItem = new ProposalItem {
                ImageId = vm.ImageId,
                ProposalId = vm.ProposalId,
                Caption = vm.Caption
            };
            // add it to the proposal
            _repository.AddProposalItem(vm.ProposalId, newProposalItem);

            // redirect to the Proposal Edit page
            return RedirectToAction("Edit", new { id = vm.ProposalId });
        }

        // GET: ToDo/Details/5
        // public ActionResult Details(int id)
        // {
        //     return View(_repository.GetToDo(id));
        // }

        // GET: ToDo/Create
        // public ActionResult Create()
        // {
        //     return View();
        // }

        // POST: ToDo/Create
        // [HttpPost]
        // [ValidateAntiForgeryToken]
        // public ActionResult Create(ToDo toDo)
        // {
        //     try
        //     {
        //         _repository.Add(toDo);
        //         return RedirectToAction(nameof(Index));
        //     }
        //     catch (Exception ex)
        //     {
        //         return ErrorView(ex);
        //     }
        // }

        // GET: ToDo/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_repository.Proposals.FirstOrDefault(p => p.Id == id));
        }

        // POST: ToDo/Edit/5
        // [HttpPost]
        // [ValidateAntiForgeryToken]
        // public ActionResult Edit(int id, ToDo toDo)
        // {
        //     try
        //     {
        //         _repository.Update(id, toDo);
        //         return RedirectToAction(nameof(Index));
        //     }
        //     catch (Exception ex)
        //     {
        //         return ErrorView(ex);
        //     }
        // }

        private ActionResult ErrorView(Exception ex)
        {
            ModelState.AddModelError(string.Empty, "Unknown Error");
            return View();
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Views/Proposal/AddProposalItem.cshtml
@model proposal_items.ViewModels.AddProposalItem
@{
    ViewData["Title"] = "Add Proposal Item";
}

<h2>Add Proposal Item</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddProposalItem" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <img src="~/images/@Model.Image.Filename" width=200 height=200/>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="ImageId" />
                <input type="hidden" asp-for="ProposalId" />
                <label asp-for="Caption" class="control-label"></label>
                <input asp-for="Caption" class="form-control" />
                <span asp-validation-for="Caption" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Proposal/Create.cshtml
@model proposal_items.Models.Proposal
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>ToDo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Proposal/Edit.cshtml
@model proposal_items.Models.Proposal
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit Proposal</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" readonly class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p>
                    <!-- NOTE: we send the proposalId along to the search page so we know
                    which proposal we're adding items to -->
                    @Html.ActionLink("Add Item", "SearchImages", new { proposalId = Model.Id })
                </p>
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                Image
                            </th>
                            <th>
                                Caption
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ProposalItems)
                        {
                            <tr>
                                <td>
                                    <img src="~/images/@item.Image.Filename" width=200 height=200 />
                                    @Html.DisplayFor(modelItem => item.Image.Filename)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Caption)
                                </td>
                                <td>
                                    <!-- NOTE these don't work properly yet -->
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Proposal/Index.cshtml
@model IEnumerable<proposal_items.Models.Proposal>

@{
    ViewData["Title"] = "Index";
}

<h2>Proposals</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Proposal/SearchImages.cshtml
@model proposal_items.ViewModels.ImageSearch

@{
    ViewData["Title"] = "ImageSearch";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

    <h4>Add Proposal Items</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <!-- NOTE the method="get" on the form action, forcing the form
            to use HTTP GET instead of POST, and pass the searchString and proposalId
            as route parameters -->
            <form asp-controller="Proposal" asp-action="SearchImages" method="get">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label @*asp-for="Search" *@ class="control-label">Search</label>
                    <input type="text" name="SearchString" />
                    <!-- NOTE the hidden field that hangs on to the proposalId because we'll need it in next step -->
                    <input type="hidden" name="ProposalId" />
                    <input type="submit" value="Search" class="form-control" />
                </div>
            </form>
        </div>
        <!-- Search Results -->
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Filename
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Images)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Filename)
                    </td>
                    <td>
                        <img height="120" width="160" src="~/images/@item.Filename"/>
                    </td>
                    <td>
                        <a asp-action="AddProposalItem" asp-route-imageId="@item.Id" asp-route-proposalId="@Model.ProposalId">Add to Proposal</a> |
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - proposal_items</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">proposal_items</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - proposal_items</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>